// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentInfoSystem.Data;

#nullable disable

namespace StudentInfoSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentInfoSystem.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal>("Marks")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Grade = "A",
                            Marks = 85.5m,
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 2,
                            Age = 19,
                            Grade = "B",
                            Marks = 78.0m,
                            Name = "Bob Smith"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            Grade = "A",
                            Marks = 92.5m,
                            Name = "Carol Davis"
                        },
                        new
                        {
                            Id = 4,
                            Age = 20,
                            Grade = "C",
                            Marks = 65.0m,
                            Name = "David Wilson"
                        },
                        new
                        {
                            Id = 5,
                            Age = 22,
                            Grade = "A",
                            Marks = 88.5m,
                            Name = "Emma Brown"
                        },
                        new
                        {
                            Id = 6,
                            Age = 19,
                            Grade = "B",
                            Marks = 72.0m,
                            Name = "Frank Miller"
                        },
                        new
                        {
                            Id = 7,
                            Age = 20,
                            Grade = "A",
                            Marks = 95.0m,
                            Name = "Grace Taylor"
                        },
                        new
                        {
                            Id = 8,
                            Age = 21,
                            Grade = "D",
                            Marks = 58.5m,
                            Name = "Henry Anderson"
                        },
                        new
                        {
                            Id = 9,
                            Age = 19,
                            Grade = "B",
                            Marks = 82.0m,
                            Name = "Ivy Garcia"
                        },
                        new
                        {
                            Id = 10,
                            Age = 20,
                            Grade = "B",
                            Marks = 76.5m,
                            Name = "Jack Martinez"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
